import { useState } from "react";
import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import "./WeeklyImage.css";

interface WeeklyImageProps {
  weekStart: string;
  weekEnd: string;
}

export default function WeeklyImage({ weekStart, weekEnd }: WeeklyImageProps) {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const weeklyImage = useQuery(api.weeklyImages.getWeeklyImage, { weekStart });
  const weekEntries = useQuery(api.weeklyImages.getWeekEntries, { weekStart, weekEnd });

  if (!weeklyImage) return null;

  const formatDateRange = (start: string, end: string) => {
    const options: Intl.DateTimeFormatOptions = { 
      month: 'short', 
      day: 'numeric',
      year: 'numeric'
    };
    const startDate = new Date(start + 'T00:00:00');
    const endDate = new Date(end + 'T00:00:00');
    
    return `${startDate.toLocaleDateString('en-US', options)} - ${endDate.toLocaleDateString('en-US', options)}`;
  };

  return (
    <>
      <div className="weekly-image-container">
        <div className="weekly-divider"></div>
        <button 
          className="weekly-image-thumbnail"
          onClick={() => setIsModalOpen(true)}
          title="View this week's collage"
        >
          <img src={weeklyImage.imageUrl} alt="Weekly collage" />
        </button>
      </div>

      {isModalOpen && (
        <div className="weekly-image-modal" onClick={() => setIsModalOpen(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <button 
              className="modal-close"
              onClick={() => setIsModalOpen(false)}
            >
              ×
            </button>
            
            <div className="modal-header">
              <h2>Things to be Happy About</h2>
              <p className="date-range">{formatDateRange(weekStart, weekEnd)}</p>
            </div>
            
            <div className="modal-body">
              <div className="image-container">
                <img src={weeklyImage.imageUrl} alt="Weekly collage" />
              </div>
              
              {weekEntries && (
                <div className="things-list">
                  <h3>{weeklyImage.thingCount} things that brought joy:</h3>
                  <ul>
                    {weekEntries?.flatMap((entry: any) => 
                      entry.things.map((thing: any, index: number) => (
                        <li key={`${entry._id}-${index}`}>{thing}</li>
                      ))
                    )}
                  </ul>
                </div>
              )}
            </div>
            
            <div className="modal-footer">
              <p className="generated-note">
                Generated by AI • {weeklyImage.thingCount} moments of happiness
              </p>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
